"use client";

import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { usePathname } from "next/navigation";
import AdminPannel from "./components/AdminPannel";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  let pathname = usePathname();

  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        {pathname.startsWith("/admin") && <AdminPannel />}
        {!pathname.startsWith("/login") && !pathname.startsWith("/admin") &&  <Navbar />}
        <div className="min-h-screen">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
